const weekRange = (start, end) => Array.from({ length: end - start + 1 }, (_, index) => start + index)

const createNumberField = (key, label, min = 0, max = 100, step = 1) => ({
  key,
  label,
  min,
  max,
  step,
})

const createSequentialNumberFields = (prefix, labelPrefix, count) =>
  Array.from({ length: count }, (_, index) => createNumberField(`${prefix}${index + 1}`, `${labelPrefix} ${index + 1}`))

const createSequentialKeys = (prefix, count) =>
  Array.from({ length: count }, (_, index) => `${prefix}${index + 1}`)

const FOUNDATION_ASSIGNMENT_MILESTONES = [
  { id: 'ga-w1', label: 'Week 1 assignment deadline', date: '2026-02-18', kind: 'deadline' },
  { id: 'ga-w2', label: 'Week 2 assignment deadline', date: '2026-02-25', kind: 'deadline' },
  { id: 'ga-w3', label: 'Week 3 assignment deadline', date: '2026-03-04', kind: 'deadline' },
  { id: 'ga-w4', label: 'Week 4 assignment deadline', date: '2026-03-11', kind: 'deadline' },
  { id: 'ga-w5', label: 'Week 5 assignment deadline', date: '2026-03-20', kind: 'deadline' },
  { id: 'ga-w6', label: 'Week 6 assignment deadline', date: '2026-03-25', kind: 'deadline' },
  { id: 'ga-w7', label: 'Week 7 assignment deadline', date: '2026-04-01', kind: 'deadline' },
  { id: 'ga-w8', label: 'Week 8 assignment deadline', date: '2026-04-08', kind: 'deadline' },
  { id: 'ga-w9', label: 'Week 9 assignment deadline', date: '2026-04-17', kind: 'deadline' },
  { id: 'ga-w10', label: 'Week 10 assignment deadline', date: '2026-04-22', kind: 'deadline' },
  { id: 'ga-w11', label: 'Week 11 assignment deadline', date: '2026-04-29', kind: 'deadline' },
  { id: 'ga-w12', label: 'Week 12 assignment deadline', date: '2026-04-29', kind: 'deadline' },
]

const DIPLOMA_ASSIGNMENT_MILESTONES = [
  { id: 'ga-w1', label: 'Week 1 assignment deadline', date: '2026-02-15', kind: 'deadline' },
  { id: 'ga-w2', label: 'Week 2 assignment deadline', date: '2026-02-22', kind: 'deadline' },
  { id: 'ga-w3', label: 'Week 3 assignment deadline', date: '2026-03-01', kind: 'deadline' },
  { id: 'ga-w4', label: 'Week 4 assignment deadline', date: '2026-03-08', kind: 'deadline' },
  { id: 'ga-w5', label: 'Week 5 assignment deadline', date: '2026-03-20', kind: 'deadline' },
  { id: 'ga-w6', label: 'Week 6 assignment deadline', date: '2026-03-22', kind: 'deadline' },
  { id: 'ga-w7', label: 'Week 7 assignment deadline', date: '2026-03-29', kind: 'deadline' },
  { id: 'ga-w8', label: 'Week 8 assignment deadline', date: '2026-04-08', kind: 'deadline' },
  { id: 'ga-w9', label: 'Week 9 assignment deadline', date: '2026-04-15', kind: 'deadline' },
  { id: 'ga-w10', label: 'Week 10 assignment deadline', date: '2026-04-19', kind: 'deadline' },
  { id: 'ga-w11', label: 'Week 11 assignment deadline', date: '2026-05-03', kind: 'deadline' },
  { id: 'ga-w12', label: 'Week 12 assignment deadline', date: '2026-05-03', kind: 'deadline' },
]

const quizWeightsPrimary = { finalWeight: 0.6, bestQuizWeight: 0.3 }
const quizWeightsSecondary = { finalWeight: 0.45, quiz1Weight: 0.25, quiz2Weight: 0.3 }
const tutorialBonus = [
  { min: 4, bonus: 1 },
  { min: 8, bonus: 2 },
  { min: 12, bonus: 3 },
]

export const JAN_2026_FOUNDATION_TERM_2 = {
  id: 'es-foundation-term-2-jan-2026',
  label: 'Jan 2026 · T1 2026',
  term: {
    level: 'T1 2026',
    term: 'Jan 2026',
    startDate: '2026-02-06',
    totalWeeks: 12,
  },
  deadlineWindowDays: 7,
  calendarEvents: [
    { id: 't1-start', label: 'Term start', date: '2026-02-06', kind: 'release' },
    { id: 't1-quiz1', label: 'Quiz 1', date: '2026-03-15', kind: 'exam' },
    { id: 't1-pq1', label: 'Programming Quiz 1', date: '2026-04-05', kind: 'deadline' },
    { id: 't1-quiz2', label: 'Quiz 2', date: '2026-04-12', kind: 'exam' },
    { id: 't1-pq2-day1', label: 'Programming Quiz 2 Day 1', date: '2026-04-26', kind: 'deadline' },
    { id: 't1-pq2-day2', label: 'Programming Quiz 2 Day 2', date: '2026-05-03', kind: 'deadline' },
    { id: 't1-endterm', label: 'End Term', date: '2026-05-10', kind: 'exam' },
    { id: 'paradox-start', label: 'Paradox starts', date: '2026-06-11', kind: 'release' },
    { id: 'paradox-end', label: 'Paradox ends', date: '2026-06-14', kind: 'deadline' },
  ],
  courses: [
    {
      id: 'eec',
      code: 'EE1103',
      shortName: 'EEC',
      name: 'Electrical & Electronic Circuits',
      level: 'foundation',
      accent: '#6be3ff',
      type: 'theory',
      weeklyItems: ['Lectures', 'Tutorial'],
      weeklyPlan: [{ item: 'GA', weeks: weekRange(1, 7) }],
      customTrackers: [],
      sessions: {
        monday: ['6:00 PM – 7:00 PM Live Session'],
        wednesday: ['6:00 PM – 8:00 PM Live Session'],
        thursday: ['6:00 PM – 7:00 PM TA Session'],
        friday: ['11:00 AM – 12:00 PM Live Session'],
      },
      milestones: [
        ...FOUNDATION_ASSIGNMENT_MILESTONES,
        { id: 'q1', label: 'Quiz 1', date: '2026-03-15', kind: 'exam' },
        { id: 'q2', label: 'Quiz 2', date: '2026-04-12', kind: 'exam' },
        { id: 'tutorials-1', label: 'Tutorials W1-4 deadline', date: '2026-03-12', kind: 'deadline' },
        { id: 'tutorials-2', label: 'Tutorials W5-8 deadline', date: '2026-04-09', kind: 'deadline' },
        { id: 'tutorials-3', label: 'Tutorials W9-12 deadline', date: '2026-05-07', kind: 'deadline' },
        { id: 'final', label: 'End Term Exam', date: '2026-05-10', kind: 'exam' },
      ],
      scoreFields: [
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'Final'),
        createNumberField('tutorialsAbove60', 'Tutorials >= 60%', 0, 12),
        ...createSequentialNumberFields('ga', 'GA', 7),
      ],
      scenarioFields: ['q2', 'final'],
      grading: {
        calculator: 'foundationTheory',
        params: {
          quizWeightsPrimary,
          quizWeightsSecondary,
          tutorialBonusKey: 'tutorialsAbove60',
          tutorialBonus,
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
            threshold: 40,
            quizKeys: ['q1', 'q2'],
          },
        },
      },
    },
    {
      id: 'bds',
      code: 'EE1102',
      shortName: 'BDS',
      name: 'Basic Digital Systems',
      level: 'foundation',
      accent: '#9d8cff',
      type: 'theory',
      weeklyItems: ['Lectures'],
      weeklyPlan: [{ item: 'GA (Handwritten)', weeks: weekRange(1, 7) }],
      customTrackers: [],
      sessions: {
        tuesday: ['4:00 PM – 5:00 PM Live Session'],
        wednesday: ['8:00 PM – 10:00 PM Live Session'],
        friday: ['6:00 PM – 7:00 PM Live Session'],
      },
      milestones: [
        ...FOUNDATION_ASSIGNMENT_MILESTONES,
        { id: 'q1', label: 'Quiz 1', date: '2026-03-15', kind: 'exam' },
        { id: 'q2', label: 'Quiz 2', date: '2026-04-12', kind: 'exam' },
        { id: 'final', label: 'End Term Exam', date: '2026-05-10', kind: 'exam' },
      ],
      scoreFields: [
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'Final'),
        ...createSequentialNumberFields('ga', 'GA', 7),
      ],
      scenarioFields: ['q2', 'final'],
      grading: {
        calculator: 'foundationTheory',
        params: {
          quizWeightsPrimary,
          quizWeightsSecondary,
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
            threshold: 40,
            quizKeys: ['q1', 'q2'],
          },
        },
      },
    },
    {
      id: 'linux',
      code: 'CS1102',
      shortName: 'Linux',
      name: 'Introduction to Linux Programming',
      level: 'foundation',
      accent: '#7ef2ba',
      type: 'theory',
      weeklyItems: ['Lectures'],
      weeklyPlan: [
        { item: 'GA', weeks: weekRange(1, 7) },
        { item: 'GRPA', weeks: weekRange(1, 7) },
        { item: 'BPT', weeks: [3, 5, 7, 10] },
      ],
      customTrackers: [],
      sessions: {
        monday: ['8:00 PM – 10:00 PM Live Session'],
        tuesday: ['9:00 PM – 11:00 PM TA Session'],
        wednesday: ['9:00 PM – 11:00 PM TA Session'],
        friday: ['9:00 PM – 11:00 PM TA Session'],
        saturday: ['2:00 PM – 4:00 PM Live Session'],
      },
      milestones: [
        ...FOUNDATION_ASSIGNMENT_MILESTONES,
        {
          id: 'bpt1',
          label: 'BPT-1 released',
          date: '2026-02-20',
          kind: 'release',
          timelineGroup: 'bpt1',
          timelineTitle: 'BPT 1',
          phaseLabel: 'Release',
        },
        {
          id: 'bpt1-deadline',
          label: 'BPT-1 deadline',
          date: '2026-03-01',
          kind: 'deadline',
          timelineGroup: 'bpt1',
          timelineTitle: 'BPT 1',
          phaseLabel: 'Due',
        },
        {
          id: 'bpt2',
          label: 'BPT-2 released',
          date: '2026-03-06',
          kind: 'release',
          timelineGroup: 'bpt2',
          timelineTitle: 'BPT 2',
          phaseLabel: 'Release',
        },
        {
          id: 'bpt2-deadline',
          label: 'BPT-2 deadline',
          date: '2026-03-15',
          kind: 'deadline',
          timelineGroup: 'bpt2',
          timelineTitle: 'BPT 2',
          phaseLabel: 'Due',
        },
        { id: 'q1', label: 'Quiz 1', date: '2026-03-15', kind: 'exam' },
        {
          id: 'bpt3',
          label: 'BPT-3 released',
          date: '2026-03-20',
          kind: 'release',
          timelineGroup: 'bpt3',
          timelineTitle: 'BPT 3',
          phaseLabel: 'Release',
        },
        {
          id: 'bpt3-deadline',
          label: 'BPT-3 deadline',
          date: '2026-03-29',
          kind: 'deadline',
          timelineGroup: 'bpt3',
          timelineTitle: 'BPT 3',
          phaseLabel: 'Due',
        },
        {
          id: 'bpt4',
          label: 'BPT-4 released',
          date: '2026-04-10',
          kind: 'release',
          timelineGroup: 'bpt4',
          timelineTitle: 'BPT 4',
          phaseLabel: 'Release',
        },
        {
          id: 'bpt4-deadline',
          label: 'BPT-4 deadline',
          date: '2026-04-19',
          kind: 'deadline',
          timelineGroup: 'bpt4',
          timelineTitle: 'BPT 4',
          phaseLabel: 'Due',
        },
        { id: 'nppe', label: 'NPPE', date: '2026-04-20', kind: 'exam' },
        { id: 'oppe', label: 'OPPE', date: '2026-04-25', kind: 'exam' },
        { id: 'final', label: 'End Term Exam', date: '2026-05-10', kind: 'exam' },
      ],
      scoreFields: [
        createNumberField('q1', 'Quiz 1'),
        {
          key: 'oppeSct',
          label: 'OPPE SCT',
          type: 'select',
          options: [
            { value: '', label: 'Select status' },
            { value: '1', label: 'Completed' },
            { value: '0', label: 'Not completed' },
          ],
        },
        createNumberField('oppe', 'OPPE'),
        createNumberField('final', 'Final'),
        createNumberField('vmt', 'VMT'),
        createNumberField('nppe', 'NPPE'),
        ...createSequentialNumberFields('bpt', 'BPT', 4),
      ],
      scenarioFields: ['oppe', 'final'],
      grading: {
        calculator: 'linuxTheory',
        params: {
          bptKeys: createSequentialKeys('bpt', 4),
          firstThreeBptKeys: createSequentialKeys('bpt', 3),
          weights: {
            q1: 0.25,
            oppe: 0.25,
            final: 0.35,
            bptAverage: 0.05,
            vmt: 0.05,
            nppe: 0.05,
          },
          eligibility: {
            sctKey: 'oppeSct',
            oppeKey: 'oppe',
            finalKey: 'final',
            threshold: 40,
          },
        },
      },
    },
    {
      id: 'embedded-c',
      code: 'CS2101',
      shortName: 'Embedded C',
      name: 'Embedded C Programming',
      level: 'foundation',
      accent: '#ff8f8f',
      type: 'theory',
      weeklyItems: ['Lectures'],
      weeklyPlan: [{ item: 'GA', weeks: weekRange(1, 6) }],
      customTrackers: [],
      sessions: {
        tuesday: ['6:00 PM – 8:00 PM Live Session'],
        friday: ['8:00 PM – 10:00 PM TA Session'],
      },
      milestones: [
        ...FOUNDATION_ASSIGNMENT_MILESTONES,
        { id: 'q1', label: 'Quiz 1', date: '2026-03-15', kind: 'exam' },
        { id: 'q2', label: 'Quiz 2', date: '2026-04-12', kind: 'exam' },
        { id: 'final', label: 'End Term Exam', date: '2026-05-10', kind: 'exam' },
      ],
      scoreFields: [
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'Final'),
        ...createSequentialNumberFields('grpa', 'GRPA', 10),
        ...createSequentialNumberFields('ga', 'GA', 6),
      ],
      scenarioFields: ['q2', 'final'],
      grading: {
        calculator: 'embeddedCTheory',
        params: {
          grpaKeys: createSequentialKeys('grpa', 10),
          grpaBestCount: 10,
          grpaWeight: 0.1,
          quizWeightsPrimary: { finalWeight: 0.5, bestQuizWeight: 0.3 },
          quizWeightsSecondary: { finalWeight: 0.4, quiz1Weight: 0.25, quiz2Weight: 0.25 },
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 6),
            bestCount: 5,
            threshold: 40,
            quizKeys: ['q1', 'q2'],
          },
        },
      },
    },
    {
      id: 'electronics-lab',
      code: 'EE1902',
      shortName: 'Electronics Lab',
      name: 'Electronics Lab',
      level: 'foundation',
      accent: '#ffd166',
      type: 'lab',
      weeklyItems: ['Video Demo', 'Lab Assignment'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: [
        {
          id: 'ol1',
          label: 'Online Lab 1 deadline',
          date: '2026-02-28',
          kind: 'deadline',
          timelineGroup: 'ol1',
          timelineTitle: 'Online Lab 1',
          phaseLabel: 'Due',
        },
        {
          id: 'ol2',
          label: 'Online Lab 2 deadline',
          date: '2026-03-07',
          kind: 'deadline',
          timelineGroup: 'ol2',
          timelineTitle: 'Online Lab 2',
          phaseLabel: 'Due',
        },
        {
          id: 'ol3',
          label: 'Online Lab 3 deadline',
          date: '2026-03-21',
          kind: 'deadline',
          timelineGroup: 'ol3',
          timelineTitle: 'Online Lab 3',
          phaseLabel: 'Due',
        },
        {
          id: 'ol4',
          label: 'Online Lab 4 deadline',
          date: '2026-03-21',
          kind: 'deadline',
          timelineGroup: 'ol4',
          timelineTitle: 'Online Lab 4',
          phaseLabel: 'Due',
        },
        {
          id: 'ol5',
          label: 'Online Lab 5 deadline',
          date: '2026-03-28',
          kind: 'deadline',
          timelineGroup: 'ol5',
          timelineTitle: 'Online Lab 5',
          phaseLabel: 'Due',
        },
        {
          id: 'ol6',
          label: 'Online Lab 6 deadline',
          date: '2026-03-28',
          kind: 'deadline',
          timelineGroup: 'ol6',
          timelineTitle: 'Online Lab 6',
          phaseLabel: 'Due',
        },
        {
          id: 'ol7',
          label: 'Online Lab 7 deadline',
          date: '2026-04-22',
          kind: 'deadline',
          timelineGroup: 'ol7',
          timelineTitle: 'Online Lab 7',
          phaseLabel: 'Due',
        },
        {
          id: 'ol8',
          label: 'Online Lab 8 deadline',
          date: '2026-04-30',
          kind: 'deadline',
          timelineGroup: 'ol8',
          timelineTitle: 'Online Lab 8',
          phaseLabel: 'Due',
        },
        { id: 'in-campus-slot-1', label: 'In-Campus Lab Slot 1 (Tentative)', date: '2026-05-25', kind: 'exam' },
        { id: 'in-campus-slot-2', label: 'In-Campus Lab Slot 2 (Tentative)', date: '2026-06-01', kind: 'exam' },
      ],
      scoreFields: [
        ...createSequentialNumberFields('ol', 'OL', 8),
        createNumberField('il', 'In-Campus Lab'),
      ],
      scenarioFields: ['il'],
      grading: {
        calculator: 'electronicsLab',
        params: {
          onlineKeys: createSequentialKeys('ol', 8),
          inPersonKey: 'il',
          onlineWeight: 0.4,
          inPersonWeight: 0.6,
          eligibility: {
            bestCount: 6,
            threshold: 40,
          },
        },
      },
    },
    {
      id: 'linux-lab',
      code: 'CS1902',
      shortName: 'Linux Lab',
      name: 'Linux Lab',
      level: 'foundation',
      accent: '#ffbd59',
      type: 'lab',
      weeklyItems: [],
      weeklyPlan: [
        { item: 'Online Lab 1', weeks: [3, 4] },
        { item: 'Online Lab 2', weeks: [5, 6] },
        { item: 'Online Lab 3', weeks: [7, 8] },
        { item: 'Online Lab 4', weeks: [10, 11] },
        { item: 'Online Lab 5', weeks: [10, 11] },
      ],
      customTrackers: [],
      sessions: {
        saturday: ['6:00 PM – 7:00 PM Lab Meeting'],
      },
      milestones: [
        {
          id: 'ol1-release',
          label: 'Online Lab 1 opens',
          date: '2026-02-27',
          kind: 'release',
          timelineGroup: 'ol1',
          timelineTitle: 'Online Lab 1',
          phaseLabel: 'Opens',
        },
        {
          id: 'ol1-deadline',
          label: 'Online Lab 1 deadline',
          date: '2026-03-08',
          kind: 'deadline',
          timelineGroup: 'ol1',
          timelineTitle: 'Online Lab 1',
          phaseLabel: 'Due',
        },
        {
          id: 'ol2-release',
          label: 'Online Lab 2 opens',
          date: '2026-03-13',
          kind: 'release',
          timelineGroup: 'ol2',
          timelineTitle: 'Online Lab 2',
          phaseLabel: 'Opens',
        },
        {
          id: 'ol2-deadline',
          label: 'Online Lab 2 deadline',
          date: '2026-03-22',
          kind: 'deadline',
          timelineGroup: 'ol2',
          timelineTitle: 'Online Lab 2',
          phaseLabel: 'Due',
        },
        {
          id: 'ol3-release',
          label: 'Online Lab 3 opens',
          date: '2026-03-27',
          kind: 'release',
          timelineGroup: 'ol3',
          timelineTitle: 'Online Lab 3',
          phaseLabel: 'Opens',
        },
        {
          id: 'ol3-deadline',
          label: 'Online Lab 3 deadline',
          date: '2026-04-05',
          kind: 'deadline',
          timelineGroup: 'ol3',
          timelineTitle: 'Online Lab 3',
          phaseLabel: 'Due',
        },
        {
          id: 'ol4-release',
          label: 'Online Lab 4 opens',
          date: '2026-04-10',
          kind: 'release',
          timelineGroup: 'ol4',
          timelineTitle: 'Online Lab 4',
          phaseLabel: 'Opens',
        },
        {
          id: 'ol4-deadline',
          label: 'Online Lab 4 deadline',
          date: '2026-04-19',
          kind: 'deadline',
          timelineGroup: 'ol4',
          timelineTitle: 'Online Lab 4',
          phaseLabel: 'Due',
        },
        {
          id: 'ol5-release',
          label: 'Online Lab 5 opens',
          date: '2026-04-10',
          kind: 'release',
          timelineGroup: 'ol5',
          timelineTitle: 'Online Lab 5',
          phaseLabel: 'Opens',
        },
        {
          id: 'ol5-deadline',
          label: 'Online Lab 5 deadline',
          date: '2026-04-19',
          kind: 'deadline',
          timelineGroup: 'ol5',
          timelineTitle: 'Online Lab 5',
          phaseLabel: 'Due',
        },
        { id: 'in-campus-slot-1', label: 'In-Campus Lab Slot 1 (Tentative)', date: '2026-05-25', kind: 'exam' },
        { id: 'in-campus-slot-2', label: 'In-Campus Lab Slot 2 (Tentative)', date: '2026-06-01', kind: 'exam' },
      ],
      scoreFields: [
        ...createSequentialNumberFields('ol', 'OL', 5),
        createNumberField('il', 'In-Campus Lab'),
      ],
      scenarioFields: ['il'],
      grading: {
        calculator: 'linuxLab',
        params: {
          onlineKeys: createSequentialKeys('ol', 5),
          inPersonKey: 'il',
          onlineWeight: 0.5,
          inPersonWeight: 0.5,
          eligibility: {
            threshold: 40,
          },
        },
      },
    },
    {
      id: 'embedded-c-lab',
      code: 'CS2901',
      shortName: 'Embedded C Lab',
      name: 'Embedded C Lab',
      level: 'foundation',
      accent: '#ff6b8a',
      type: 'lab',
      weeklyItems: [],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: [
        { id: 'in-campus-slot-1', label: 'In-Campus Lab Slot 1 (Tentative)', date: '2026-05-25', kind: 'exam' },
        { id: 'in-campus-slot-2', label: 'In-Campus Lab Slot 2 (Tentative)', date: '2026-06-01', kind: 'exam' },
      ],
      scoreFields: [
        createNumberField('attendance', 'Attendance'),
        createNumberField('viva', 'Lab experiment + Viva'),
      ],
      scenarioFields: ['viva'],
      grading: {
        calculator: 'embeddedCLab',
        params: {
          attendanceKey: 'attendance',
          vivaKey: 'viva',
          attendanceWeight: 0.2,
          vivaWeight: 0.8,
        },
      },
    },

    // ═══════════════════════════════════════
    // DIPLOMA LEVEL COURSES
    // ═══════════════════════════════════════

    {
      id: 'signals',
      code: 'EE2101',
      shortName: 'S&S',
      name: 'Signals and Systems',
      level: 'diploma',
      accent: '#FF6D00',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA', 10),
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['q1', 'q2', 'final'],
      grading: {
        calculator: 'diplomaTheoryGAA',
        params: {
          gaaKeys: createSequentialKeys('ga', 10),
          gaaWeight: 0.05,
          quizWeightsPrimary: { finalWeight: 0.6, bestQuizWeight: 0.25 },
          quizWeightsSecondary: { finalWeight: 0.4, quiz1Weight: 0.25, quiz2Weight: 0.3 },
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
          },
        },
      },
    },
    {
      id: 'python',
      code: 'CS1002',
      shortName: 'Python',
      name: 'Python Programming',
      level: 'diploma',
      accent: '#2D5BFF',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment', 'GrPA'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA (Obj)', 10),
        ...createSequentialNumberFields('grpa', 'GrPA', 10),
        createNumberField('q1', 'Quiz 1'),
        createNumberField('pe1', 'OPPE 1'),
        createNumberField('pe2', 'OPPE 2'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['q1', 'pe1', 'pe2', 'final'],
      grading: {
        calculator: 'pythonTheory',
        params: {
          gaa1Keys: createSequentialKeys('ga', 10),
          gaa2Keys: createSequentialKeys('grpa', 10),
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
          },
        },
      },
    },
    {
      id: 'analog',
      code: 'EE2102',
      shortName: 'AES',
      name: 'Analog Electronic Systems',
      level: 'diploma',
      accent: '#FF2D78',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA', 10),
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['q1', 'q2', 'final'],
      grading: {
        calculator: 'diplomaTheoryGAA',
        params: {
          gaaKeys: createSequentialKeys('ga', 10),
          gaaWeight: 0.05,
          quizWeightsPrimary: { finalWeight: 0.6, bestQuizWeight: 0.25 },
          quizWeightsSecondary: { finalWeight: 0.4, quiz1Weight: 0.25, quiz2Weight: 0.3 },
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
          },
        },
      },
    },
    {
      id: 'analog-lab',
      code: 'EE2901',
      shortName: 'AES Lab',
      name: 'Analog Electronics Laboratory',
      level: 'diploma',
      accent: '#FF2D78',
      type: 'lab',
      weeklyItems: [],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: [
        { id: 'ol1', label: 'Online Lab 1 deadline', date: '2026-02-28', kind: 'deadline' },
        { id: 'ol2', label: 'Online Lab 2 deadline', date: '2026-03-07', kind: 'deadline' },
        { id: 'ol3', label: 'Online Lab 3 deadline', date: '2026-03-21', kind: 'deadline' },
        { id: 'ol4', label: 'Online Lab 4 deadline', date: '2026-03-28', kind: 'deadline' },
        { id: 'ol5', label: 'Online Lab 5 deadline', date: '2026-04-22', kind: 'deadline' },
        { id: 'in-campus', label: 'In-Campus Lab (Tentative)', date: '2026-05-25', kind: 'exam' },
      ],
      scoreFields: [
        ...createSequentialNumberFields('ol', 'Online Lab', 5),
        createNumberField('il', 'In-Person Lab'),
      ],
      scenarioFields: ['il'],
      grading: {
        calculator: 'electronicsLab',
        params: {
          onlineKeys: createSequentialKeys('ol', 5),
          inPersonKey: 'il',
          onlineWeight: 0.4,
          inPersonWeight: 0.6,
          eligibility: { bestCount: 4 },
        },
      },
    },
    {
      id: 'dsp',
      code: 'EE3101',
      shortName: 'DSP',
      name: 'Digital Signal Processing',
      level: 'diploma',
      accent: '#7C4DFF',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment', 'Lab Experiment'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA', 10),
        ...createSequentialNumberFields('le', 'Lab Experiment', 8),
        createNumberField('olex', 'Online Lab Exam'),
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['q1', 'q2', 'final'],
      grading: {
        calculator: 'dspTheory',
        params: {
          gaaKeys: createSequentialKeys('ga', 10),
          labKeys: createSequentialKeys('le', 8),
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
          },
        },
      },
    },
    {
      id: 'sensors',
      code: 'EE3103',
      shortName: 'Sensors',
      name: 'Sensors and Applications',
      level: 'diploma',
      accent: '#00C853',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA', 10),
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['q1', 'q2', 'final'],
      grading: {
        calculator: 'diplomaTheoryGAA',
        params: {
          gaaKeys: createSequentialKeys('ga', 10),
          gaaWeight: 0.05,
          quizWeightsPrimary: { finalWeight: 0.6, bestQuizWeight: 0.25 },
          quizWeightsSecondary: { finalWeight: 0.4, quiz1Weight: 0.25, quiz2Weight: 0.3 },
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
          },
        },
      },
    },
    {
      id: 'dsd',
      code: 'EE2103',
      shortName: 'DSD',
      name: 'Digital System Design',
      level: 'diploma',
      accent: '#00E5FF',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA', 10),
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['q1', 'q2', 'final'],
      grading: {
        calculator: 'diplomaTheoryGAA',
        params: {
          gaaKeys: createSequentialKeys('ga', 10),
          gaaWeight: 0.05,
          quizWeightsPrimary: { finalWeight: 0.6, bestQuizWeight: 0.25 },
          quizWeightsSecondary: { finalWeight: 0.5, quiz1Weight: 0.2, quiz2Weight: 0.25 },
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
          },
        },
      },
    },
    {
      id: 'dsd-lab',
      code: 'EE2902',
      shortName: 'DSD Lab',
      name: 'Digital System Design Laboratory',
      level: 'diploma',
      accent: '#00E5FF',
      type: 'lab',
      weeklyItems: [],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: [
        { id: 'wl1', label: 'Weekly Lab 1 deadline', date: '2026-03-04', kind: 'deadline' },
        { id: 'wl2', label: 'Weekly Lab 2 deadline', date: '2026-03-11', kind: 'deadline' },
        { id: 'wl3', label: 'Weekly Lab 3 deadline', date: '2026-03-20', kind: 'deadline' },
        { id: 'wl4', label: 'Weekly Lab 4 deadline', date: '2026-03-22', kind: 'deadline' },
        { id: 'wl5', label: 'Weekly Lab 5 deadline', date: '2026-03-29', kind: 'deadline' },
        { id: 'wl6', label: 'Weekly Lab 6 deadline', date: '2026-04-08', kind: 'deadline' },
        { id: 'wl7', label: 'Weekly Lab 7 deadline', date: '2026-04-15', kind: 'deadline' },
        { id: 'in-campus', label: 'In-Campus Lab (Tentative)', date: '2026-05-25', kind: 'exam' },
      ],
      scoreFields: [
        ...createSequentialNumberFields('ol', 'Weekly Lab', 7),
        createNumberField('il', 'In-Person Lab'),
      ],
      scenarioFields: ['il'],
      grading: {
        calculator: 'dsdLab',
        params: {
          onlineKeys: createSequentialKeys('ol', 7),
          inPersonKey: 'il',
          eligibility: { bestCount: 7 },
        },
      },
    },
    {
      id: 'comporg',
      code: 'EE2104',
      shortName: 'CompOrg',
      name: 'Computer Organisation',
      level: 'diploma',
      accent: '#FFE13A',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA', 10),
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['q1', 'q2', 'final'],
      grading: {
        calculator: 'diplomaTheoryGAA',
        params: {
          gaaKeys: createSequentialKeys('ga', 10),
          gaaWeight: 0.05,
          quizWeightsPrimary: { finalWeight: 0.6, bestQuizWeight: 0.25 },
          quizWeightsSecondary: { finalWeight: 0.5, quiz1Weight: 0.2, quiz2Weight: 0.25 },
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
          },
        },
      },
    },
    {
      id: 'etm',
      code: 'EE2105',
      shortName: 'ETM',
      name: 'Electronic Testing and Measurement',
      level: 'diploma',
      accent: '#FF4D4D',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA', 10),
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['q1', 'q2', 'final'],
      grading: {
        calculator: 'diplomaTheoryGAA10pct',
        params: {
          gaaKeys: createSequentialKeys('ga', 10),
          quizWeightsPrimary: { finalWeight: 0.6, bestQuizWeight: 0.2 },
          quizWeightsSecondary: { finalWeight: 0.5, quiz1Weight: 0.2, quiz2Weight: 0.2 },
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 6),
            bestCount: 5,
          },
        },
      },
    },

    // ═══════════════════════════════════════
    // DEGREE LEVEL COURSES
    // ═══════════════════════════════════════

    {
      id: 'control',
      code: 'EE3102',
      shortName: 'Control',
      name: 'Control Engineering',
      level: 'degree',
      accent: '#2D5BFF',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA', 10),
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('design', 'Design Assignment (Matlab)'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['q1', 'q2', 'design', 'final'],
      grading: {
        calculator: 'controlTheory',
        params: {
          gaaKeys: createSequentialKeys('ga', 10),
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
          },
        },
      },
    },
    {
      id: 'emft',
      code: 'EE3104',
      shortName: 'EMFT',
      name: 'Electromagnetic Fields & Transmission Lines',
      level: 'degree',
      accent: '#FF6D00',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA', 10),
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['q1', 'q2', 'final'],
      grading: {
        calculator: 'diplomaTheoryGAA10pct',
        params: {
          gaaKeys: createSequentialKeys('ga', 10),
          quizWeightsPrimary: { finalWeight: 0.6, bestQuizWeight: 0.2 },
          quizWeightsSecondary: { finalWeight: 0.4, quiz1Weight: 0.2, quiz2Weight: 0.3 },
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
          },
        },
      },
    },
    {
      id: 'epd',
      code: 'EE4102',
      shortName: 'EPD',
      name: 'Electronic Product Design',
      level: 'degree',
      accent: '#FF2D78',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA', 10),
        createNumberField('q1', 'Quiz 1 (out of 40, scaled)'),
        createNumberField('q2', 'Quiz 2 (out of 40, scaled)'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['q1', 'q2', 'final'],
      grading: {
        calculator: 'epdTheory',
        params: {
          gaaKeys: createSequentialKeys('ga', 10),
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
          },
        },
      },
    },
    {
      id: 'spg',
      code: 'GN3001',
      shortName: 'SPG',
      name: 'Strategies for Professional Growth',
      level: 'degree',
      accent: '#00C853',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment', 'Group Project'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA', 10),
        createNumberField('gp', 'Group Project'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['gp', 'q2', 'final'],
      grading: {
        calculator: 'spgTheory',
        params: {
          gaaKeys: createSequentialKeys('ga', 10),
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
            quizKeys: ['q2'],
          },
        },
      },
    },
    {
      id: 'elfpga',
      code: 'EE4101',
      shortName: 'EL&FPGA',
      name: 'Embedded Linux and FPGAs',
      level: 'degree',
      accent: '#7C4DFF',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA', 10),
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['q1', 'q2', 'final'],
      grading: {
        calculator: 'diplomaTheoryGAA10pct',
        params: {
          gaaKeys: createSequentialKeys('ga', 10),
          quizWeightsPrimary: { finalWeight: 0.5, bestQuizWeight: 0.2 },
          quizWeightsSecondary: { finalWeight: 0.4, quiz1Weight: 0.25, quiz2Weight: 0.25 },
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 6),
            bestCount: 5,
          },
        },
      },
    },
    {
      id: 'elfpga-lab',
      code: 'EE4901',
      shortName: 'EL&FPGA Lab',
      name: 'Embedded Linux and FPGAs Lab',
      level: 'degree',
      accent: '#7C4DFF',
      type: 'lab',
      weeklyItems: [],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: [
        { id: 'in-campus-slot-1', label: 'In-Campus Lab Slot 1 (Tentative)', date: '2026-05-25', kind: 'exam' },
        { id: 'in-campus-slot-2', label: 'In-Campus Lab Slot 2 (Tentative)', date: '2026-06-01', kind: 'exam' },
      ],
      scoreFields: [
        createNumberField('attendance', 'Attendance'),
        createNumberField('viva', 'Lab experiment + Viva'),
      ],
      scenarioFields: ['viva'],
      grading: {
        calculator: 'embeddedCLab',
        params: {
          attendanceKey: 'attendance',
          vivaKey: 'viva',
          attendanceWeight: 0.2,
          vivaWeight: 0.8,
        },
      },
    },
    {
      id: 'dicdesign',
      code: 'EE5102',
      shortName: 'DICD',
      name: 'Digital IC Design',
      level: 'degree',
      accent: '#00E5FF',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA', 10),
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['q1', 'q2', 'final'],
      grading: {
        calculator: 'diplomaTheoryGAA10pct',
        params: {
          gaaKeys: createSequentialKeys('ga', 10),
          quizWeightsPrimary: { finalWeight: 0.6, bestQuizWeight: 0.2 },
          quizWeightsSecondary: { finalWeight: 0.4, quiz1Weight: 0.2, quiz2Weight: 0.3 },
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
          },
        },
      },
    },
    {
      id: 'probstats',
      code: 'MA3101',
      shortName: 'P&S',
      name: 'Probability and Statistics',
      level: 'degree',
      accent: '#FFE13A',
      type: 'theory',
      weeklyItems: ['Lectures', 'Graded Assignment'],
      weeklyPlan: [],
      customTrackers: [],
      sessions: {},
      milestones: DIPLOMA_ASSIGNMENT_MILESTONES,
      scoreFields: [
        ...createSequentialNumberFields('ga', 'GA', 10),
        createNumberField('q1', 'Quiz 1'),
        createNumberField('q2', 'Quiz 2'),
        createNumberField('final', 'End Term'),
      ],
      scenarioFields: ['q1', 'q2', 'final'],
      grading: {
        calculator: 'diplomaTheoryGAA10pct',
        params: {
          gaaKeys: createSequentialKeys('ga', 10),
          quizWeightsPrimary: { finalWeight: 0.6, bestQuizWeight: 0.2 },
          quizWeightsSecondary: { finalWeight: 0.4, quiz1Weight: 0.2, quiz2Weight: 0.3 },
          eligibility: {
            assignmentKeys: createSequentialKeys('ga', 7),
            bestCount: 5,
          },
        },
      },
    },
  ],
}
